server:
  port: 8080
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: MainControllerService
          uri: http://localhost:8080
          predicates:
            - Path=/Chats/**